import type { Metadata } from "next";
import { Bungee, Space_Mono } from 'next/font/google'
import "./globals.css";
import { Toaster } from "@/components/ui";

const bungee = Bungee({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-bungee',
})

const spaceMono = Space_Mono({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-space-mono',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bungee.variable} ${spaceMono.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
